Table users {
  id integer [primary key]
  first_name varchar
  last_name varchar
  public_username varchar
  secret_username varchar
  created_at timestamp
}

Table user_squads {
  id integer [primary key]
  user_id integer
  player_id integer
  created_at timestamp
}

Table players {
  id integer [primary key]
  name varchar
  position varchar // GK, DEF, MID, FWD
  club_id integer
  squad_id integer
}

Table club {
  id integer [primary key]
  name varchar
}

Ref squad_players: players.squad_id <> user_squads.id
Ref club_players: players.club_id - club.id
Ref users_squad: user_squads.user_id - users.id


//------------------------------------------------------
// ROUNDS
//------------------------------------------------------
Table rounds {
  id integer [primary key]
  round_number integer // 1..(teams-1) + rematch rounds
}

//------------------------------------------------------
// MATCHES
//------------------------------------------------------
Table matches {
  id integer [primary key]
  home_team_id integer
  away_team_id integer
  round_id integer
  start_time timestamp
  status varchar
}

Ref: club.id < matches.home_team_id
Ref: club.id < matches.away_team_id
Ref: rounds.id < matches.round_id


//------------------------------------------------------
// MATCH EVENTS
//------------------------------------------------------
Table match_events {
  id integer [primary key]
  match_id integer
  player_id integer
  minute integer
  type varchar // must match scoring_rules.event_type
}

Ref: matches.id < match_events.match_id
Ref: players.id < match_events.player_id


//------------------------------------------------------
// USER POINTS (MATCH-LEVEL)
//------------------------------------------------------
Table user_points {
  id integer [primary key]
  user_squad_id integer
  match_id integer
  points integer
}

Ref: user_points.user_squad_id > user_squads.id
Ref: user_points.match_id > matches.id


//------------------------------------------------------
// USER POINTS (ROUND-LEVEL AGGREGATE)
//------------------------------------------------------
Table user_round_points {
  id integer [primary key]
  user_id integer
  round_id integer
  total_points integer
}

Ref: user_round_points.user_id > users.id
Ref: user_round_points.round_id > rounds.id


//------------------------------------------------------
// PLAYER POINTS PER ROUND
//------------------------------------------------------
Table player_round_points {
  id integer [primary key]
  player_id integer
  round_id integer
  total_points integer
}

Ref: player_round_points.player_id > players.id
Ref: player_round_points.round_id > rounds.id


//------------------------------------------------------
// SCORING RULES
//------------------------------------------------------
Table scoring_rules {
  id integer [primary key]
  event_type varchar
  points integer
}
